config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :users
  root 'welcome#index'

  mount ApiRoot => ApiRoot::PREFIX

  resources :courses, only: [:index, :show] do
    member do
        post :buy
    end
  end

  namespace :admin do 
    resources :courses
  end
end

app/models/admin.rb
class Admin < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/api_access_token.rb
class ApiAccessToken < ApplicationRecord
  belongs_to :admin

  before_create :generate_keys

  private

  def generate_keys
    begin
      self.key = SecureRandom.urlsafe_base64(30).tr('_-', 'xx')
    end while ApiAccessToken.where(key: key).any?
  end
end

app/models/api_access_user_token.rb
class ApiAccessUserToken < ApplicationRecord
  belongs_to :user

  before_create :generate_keys

  private

  def generate_keys
    begin
      self.key = SecureRandom.urlsafe_base64(30).tr('_-', 'xx')
    end while ApiAccessToken.where(key: key).any?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :orders
  belongs_to :users, optional: true

  enum category: [:國文, :英文, :數學, :歷史, :地理, :公民, :物理, :化學, :其它]
  enum currency: [:TWD, :USD, :JPY, :EURO, :others]

  def to_param
    self.friendly_id
  end

  def has_user(user)
    self.orders.where( :user_id => user.id ).first
  end


  validates_presence_of :title, :friendly_id
  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :course

  def course_expired
    Time.now <= self.created_at.localtime + self.course.duration.day
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  has_many :courses, through: :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  layout "backend"

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.create(course_params)

    if @course.save
      redirect_to admin_courses_path, notice: '新增課程成功'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to admin_courses_path, notice: "修改成功" 
    else
      render :edit
    end

  end

  def destroy
  end

  private

  def course_params
    params.require(:course).permit(:title, :category, :price, :currency, :available, :duration, :friendly_id, :video, :intro)
  end

  def set_course
    @course = Course.find_by_friendly_id!(params[:id])
  end

end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  layout "backend"
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  layout "backend"
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  layout "backend"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  layout "backend"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  layout "backend"
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = current_user.courses.all
    @orders = current_user.orders.all
  end

  def show
    @course = Course.find_by(friendly_id: params[:id])
  end

  def buy
    unless current_user
        redirect_to new_user_session_path, alert: "請先登入帳號"
    else
      @course = Course.find_by(friendly_id: params[:id])
      order = Order.find_by(user: current_user, course: @course)
      unless @course.has_user(current_user) && order.course_expired
        @order = Order.create( user: current_user, course: @course)
        if @order.save
          redirect_to root_path
        else 
          redirect_to course_path(@course)
        end
      else
        redirect_to course_path(@course), alert: "已經購買過了"
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @courses = Course.where(available: true)
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-white text-gray-600 work-sans leading-normal text-base tracking-normal">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>
    <%= render 'shared/frontend/navbar' %>
    <%= yield %>
    <%= render 'shared/frontend/footer' %>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-white text-gray-600 work-sans leading-normal text-base tracking-normal">
    <%= render 'shared/backend/navbar' %>
    <p style="color: green"><%= flash[:notice] %></p>
    <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
    <%= render 'shared/backend/footer' %>
  </body>
</html>

app/views/shared/backend/_footer.html.erb
<footer class="bg-gray-100 text-center lg:text-left">
  <div class="container p-6 text-gray-800">
    <div class="grid lg:grid-cols-2 gap-4">
      <div class="mb-6 md:mb-0">
        <h5 class="font-medium mb-2 uppercase">僅供DEMO使用</h5>

        <p class="mb-4">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
          molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
          aliquam voluptatem veniam, est atque cumque eum delectus sint!
        </p>
      </div>

      <div class="mb-6 md:mb-0">
        <h5 class="font-medium mb-2 uppercase">僅供DEMO使用</h5>

        <p class="mb-4">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
          molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
          aliquam voluptatem veniam, est atque cumque eum delectus sint!
        </p>
      </div>
    </div>
  </div>

  <div class="text-center text-gray-700 p-4" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-gray-800" href="https://tailwind-elements.com/">LAICHU</a>
  </div>
</footer>

app/views/shared/backend/_navbar.html.erb
<div class="relative bg-blue-300 h-20 ">
  <div class=" h-20 mx-auto px-2 sm:px-6">
    <div class="max-w-full bg-blue-300 h-20 navbar">
      <div class="mx-2 px-2 h-20">
        <div class="flex border-gray-100 h-full">
          <div class="self-center w-3/12">
            <div class="w-1/10">
              <% if current_admin.present? %>
                <%= link_to "課程後台管理系統", admin_courses_path, class:"text-white text-2xl subpixel-antialiased " %>
              <% else %>
                <%= link_to "課程後台管理系統", new_admin_registration_path, class:"text-white text-2xl subpixel-antialiased " %>
              <% end %>
            </div>
          </div>

             <div class="flex" style="width: 70%" >
              <div class="w-36 hidden md:flex items-center justify-end md:flex-1 lg:w-0">
                <% if signed_in? && current_admin %>
                  <div class="whitespace-nowrap text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md">
                    <%= link_to "變更#{current_admin.email }資料", edit_admin_registration_path(current_admin) %>
                  </div>
                <% end %>

                  <div class=" text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md">
                    <%= link_to "回前台首頁", root_path %>
                  </div>


                  <% if signed_in? %>
                    <div class=" text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md">
                      <%= link_to "登出", destroy_admin_session_path, method: 'delete', class:"" %>
                    </div>
                    <% else %>
                    <div>
                    <%= link_to "登入", admin_session_path, class:"whitespace-nowrap text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md" %>
                    </div>
                    <div>
                    <%= link_to "註冊", new_admin_registration_path, class:"whitespace-nowrap text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md" %>
                    </div>
                  <% end %>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/frontend/_footer.html.erb
<footer class="bg-gray-100 text-center lg:text-left">
  <div class="container p-6 text-gray-800">
    <div class="grid lg:grid-cols-2 gap-4">
      <div class="mb-6 md:mb-0">
        <h5 class="font-medium mb-2 uppercase">僅供DEMO使用</h5>

        <p class="mb-4">
          家教網測試用footer
        </p>
        <p class="mb-4 text-green-600">
          <%= link_to "家教網後台", admin_courses_path %>
        </p>
      </div>

      <div class="mb-6 md:mb-0">
        <h5 class="font-medium mb-2 uppercase">僅供DEMO使用</h5>

        <p class="mb-4">
          家教網測試用footer
        </p>
      </div>
    </div>
  </div>

  <div class="text-center text-gray-700 p-4" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-gray-800" href="https://tailwind-elements.com/">LAICHU</a>
  </div>
</footer>

app/views/shared/frontend/_navbar.html.erb
<div class="relative bg-green-300 h-20 ">
  <div class=" h-20 mx-auto px-2 sm:px-6">
    <div class="max-w-full bg-green-300 h-20 navbar">
      <div class="mx-2 px-2 h-20">
        <div class="flex border-gray-100 h-full">
          <div class="self-center w-3/12">
            <div class="w-1/10">
              <%= link_to "家教網", root_path, class:"text-white text-2xl subpixel-antialiased " %>
            </div>
          </div>

             <div class="flex" style="width: 70%" >
              <div class="w-36 hidden md:flex items-center justify-end md:flex-1 lg:w-0">
                <% if signed_in? && current_user %>
                  <div class="whitespace-nowrap text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md">
                    <%= link_to "變更#{current_user.email }資料", edit_admin_registration_path(current_admin) %>
                  </div>
                <% end %>


                  <% if signed_in? && current_user %>
                    <div class=" text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md">
                      <%= link_to "登出", destroy_user_session_path, method: 'delete', class:"" %>
                    </div>
                    <div class=" text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md">
                    <%= link_to "我的課程", courses_path, class:"" %>
                    </div>
                    <% else %>
                    <div>
                    <%= link_to "登入", user_session_path, class:"whitespace-nowrap text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md" %>
                    </div>
                    <div>
                    <%= link_to "註冊", new_user_registration_path, class:"whitespace-nowrap text-base font-medium text-gray-500 bg-white hover:text-gray-900 p-2 m-1 rounded-md" %>
                    </div>
                  <% end %>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>